sudo: false
dist: trusty
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libasound2-dev
      - libxinerama-dev
      - libgl1-mesa-dev-lts-xenial
      - libxi-dev
language: cpp
before_script:
  - git submodule update --init --recursive
  - git clone https://github.com/Kode/nodejs_bin.git --depth 1
  - nodejs_bin/copysysbin.sh
script:
  - nodejs_bin/node make.js html5 --kha . --from Tests/Empty
  - nodejs_bin/node make.js krom --kha . --from Tests/Empty
  - nodejs_bin/node make.js android --kha . --from Tests/Empty
  - nodejs_bin/node make.js flash --kha . --from Tests/Empty
  - nodejs_bin/node make.js --kha . --from Tests/Empty --compile
